### PR TITLE
Add CMake 3.17.0

### PR DESCRIPTION
**Pull request by KGHustad**
This PR adds CMake 3.17, which brings some improvements for CUDA linking. 
https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html#cmake-317--more-cuda

I noticed that `ccmake` was not built for the installed version of CMake 3.15.2, presumably because ncurses wasn't installed (via apt) on eX3 at that time, but it is now. I tried rebuilding CMake 3.15.2 now, and ncurses is detected correctly.

I suppose we could replace 3.15.2 with 3.17.0 in the `build_deps` files, but I've left them untouched for now. @jamtrott, do you think there's any point in keeping the older 3.15.2 version in the repo? As CMake is always a build dependency, we shouldn't run into any issues if we remove older versions of CMake that have been used to build other modules.

### CODE REVIEW

**Comment by jamtrott** [comment]
> This PR adds CMake 3.17, which brings some improvements for CUDA linking.
> https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html#cmake-317--more-cuda
> 

That looks useful.

> I noticed that `ccmake` was not built for the installed version of CMake 3.15.2, presumably because ncurses wasn't installed (via apt) on eX3 at that time, but it is now. I tried rebuilding CMake 3.15.2 now, and ncurses is detected correctly.

Good. Do you need to add ncurses to `build_deps`?

> 
> I suppose we could replace 3.15.2 with 3.17.0 in the `build_deps` files, but I've left them untouched for now. @jamtrott, do you think there's any point in keeping the older 3.15.2 version in the repo? As CMake is always a build dependency, we shouldn't run into any issues if we remove older versions of CMake that have been used to build other modules.

You mean that whenever CMake is a dependency it is always a build dependency, and never a run-time dependency/prerequisite, right?

I think it would be an advantage to replace the old version and just keep 3.17.0.  That should be possible with a find and replace using `git grep` and `sed`.  It might also be worth testing the entire build, just in case any of the modules that use CMake run into issues.  Would you like to give it a try?

**Comment by KGHustad** [comment]
> > I noticed that `ccmake` was not built for the installed version of CMake 3.15.2, presumably because ncurses wasn't installed (via apt) on eX3 at that time, but it is now. I tried rebuilding CMake 3.15.2 now, and ncurses is detected correctly.
> 
> Good. Do you need to add ncurses to `build_deps`?

That would be a cleaner approach, although `ccmake` is not needed to build any of the modules. 
It's a bit mysterious that `ccmake` is built if ncurses is installed through other means (e.g. the system package manager), and it could potentially break if that ncurses installation is changed.
ncurses is used for many tools, so it's definitely useful have in the module system.

> > I suppose we could replace 3.15.2 with 3.17.0 in the `build_deps` files, but I've left them untouched for now. @jamtrott, do you think there's any point in keeping the older 3.15.2 version in the repo? As CMake is always a build dependency, we shouldn't run into any issues if we remove older versions of CMake that have been used to build other modules.
> 
> You mean that whenever CMake is a dependency it is always a build dependency, and never a run-time dependency/prerequisite, right?

Exactly.
> I think it would be an advantage to replace the old version and just keep 3.17.0. That should be possible with a find and replace using `git grep` and `sed`. It might also be worth testing the entire build, just in case any of the modules that use CMake run into issues. Would you like to give it a try?

Ok, then I'll replace 3.15.2 with 3.17.0, rebuild everything, and check that it works.

**Comment by jamtrott** [comment]
> [...]
> 
> That would be a cleaner approach, although `ccmake` is not needed to build any of the modules.
> It's a bit mysterious that `ccmake` is built if ncurses is installed through other means (e.g. the system package manager), and it could potentially break if that ncurses installation is changed.
> ncurses is used for many tools, so it's definitely useful have in the module system.
> 

There is a module for ncurses already, so it should be a simple matter of adding `ncurses/6.1` to `build_deps`, I think.

> [...]
> Ok, then I'll replace 3.15.2 with 3.17.0, rebuild everything, and check that it works.

Great, good luck!

**Comment by KGHustad** [comment]
I had some trouble with bootstrapping CMake 3.17.0 on aarch64. For some reason it seems to ignore `--no-system-libs` flag and complains that it cannot find OpenSSL. 

3.15.2 seems to link OpenSSL statically on aarch64, while it's linked dynamically to the system OpenSSL on x86.

## aarch64
```
$ ldd /cm/shared/ex3-modules/apps/cmake/3.15.2/bin/cmake
        linux-vdso.so.1 (0x0000fffff7ffc000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000fffff7868000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000fffff783c000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000fffff76a9000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000fffff75ef000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000fffff75cb000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000fffff7472000)
        /lib/ld-linux-aarch64.so.1 (0x0000fffff7fd1000)
```

## x86
```
$ ldd /cm/shared/ex3-modules/apps/cmake/3.15.2/bin/cmake
        linux-vdso.so.1 (0x00007ffff7ffa000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007ffff714c000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ffff6c81000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffff6a7d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffff6875000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffff6656000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffff62cd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffff5f2f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffff5d17000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffff5926000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffff7dd5000)
```

It seems that this issue was introduced with CMake 3.16, as it not bootstrap on aarch64 either.
I think this needs to be fixed upstream, so I suggest that we just close this pull request for now.

**Comment by KGHustad** [comment]
For the record, the x86 rebuild of all modules completed successfully.

**Comment by jamtrott** [comment]
> I had some trouble with bootstrapping CMake 3.17.0 on aarch64. For some reason it seems to ignore `--no-system-libs` flag and complains that it cannot find OpenSSL.
> 
> 3.15.2 seems to link OpenSSL statically on aarch64, while it's linked dynamically to the system OpenSSL on x86.
> 
> ## aarch64
> ```
> $ ldd /cm/shared/ex3-modules/apps/cmake/3.15.2/bin/cmake
>         linux-vdso.so.1 (0x0000fffff7ffc000)
>         libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000fffff7868000)
>         libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000fffff783c000)
>         libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000fffff76a9000)
>         libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000fffff75ef000)
>         libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000fffff75cb000)
>         libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000fffff7472000)
>         /lib/ld-linux-aarch64.so.1 (0x0000fffff7fd1000)
> ```
> 
> ## x86
> ```
> $ ldd /cm/shared/ex3-modules/apps/cmake/3.15.2/bin/cmake
>         linux-vdso.so.1 (0x00007ffff7ffa000)
>         libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007ffff714c000)
>         libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ffff6c81000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffff6a7d000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffff6875000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffff6656000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffff62cd000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffff5f2f000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffff5d17000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffff5926000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007ffff7dd5000)
> ```
> 
> It seems that this issue was introduced with CMake 3.16, as it not bootstrap on aarch64 either.
> I think this needs to be fixed upstream, so I suggest that we just close this pull request for now.


OK, thanks for trying.

In this case, maybe it's a good idea to wait for a fix from upstream.  In general, there are other situations where it is useful to distinguish between x86 and aarch64.  Maybe it would be easier to do so if we had separate branches for each architecture?  For example, the CUDA-related modules are only relevant for x86.

Do you have any thoughts about this?  It's something we can get back to at a later point anyway, if necessary.

**Comment by KGHustad** [comment]
I do see the use of distinguishing between x86 and aarch64. However, I fear that having two branches would double the amount of work required to maintain the repository. Most modules should be able to build with identical build scripts, which is what we currently do. If we had some way to mark a module as being compatible with only certain architectures, we could at least handle the CUDA module that way. But for the case in this issue, where we could use 3.17.0 for x86, but not for aarch64, using different branches seems like the best way to work around that.

**Pull request closed without merging**
